app_id: honeygain
name: Honeygain
docker_image: honeygain/honeygain:latest
description: Share your unused internet bandwidth and earn passive income with Honeygain.
proxy_support: true
supported_platforms:
  - linux
  - windows
  - macos
environment_vars:
  - key: HONEYGAIN_EMAIL
    required: true
    description: "Your Honeygain account email"
  - key: HONEYGAIN_PASSWORD
    required: true
    description: "Your Honeygain account password"
  - key: HONEYGAIN_DEVICE_NAME
    required: false
    description: "Custom device name (optional)"
network_mode: bridge
health_check:
  endpoint: "http://localhost:8080"
  interval: "30s"
resource_limits:
  cpu: "0.5"
  memory: "256m"

