// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeployApp(arg1, arg2) {
  return window['go']['api']['AppsAPI']['DeployApp'](arg1, arg2);
}

export function DeployAppWithProxies(arg1, arg2, arg3) {
  return window['go']['api']['AppsAPI']['DeployAppWithProxies'](arg1, arg2, arg3);
}

export function DeployAppWithProxiesSelective(arg1, arg2, arg3) {
  return window['go']['api']['AppsAPI']['DeployAppWithProxiesSelective'](arg1, arg2, arg3);
}

export function DeployAppWithProxy(arg1) {
  return window['go']['api']['AppsAPI']['DeployAppWithProxy'](arg1);
}

export function DeployAppWithProxyId(arg1, arg2, arg3) {
  return window['go']['api']['AppsAPI']['DeployAppWithProxyId'](arg1, arg2, arg3);
}

export function GetAppCredentials(arg1) {
  return window['go']['api']['AppsAPI']['GetAppCredentials'](arg1);
}

export function GetAppInstances(arg1) {
  return window['go']['api']['AppsAPI']['GetAppInstances'](arg1);
}

export function GetAppLogs(arg1, arg2) {
  return window['go']['api']['AppsAPI']['GetAppLogs'](arg1, arg2);
}

export function GetAppStats(arg1) {
  return window['go']['api']['AppsAPI']['GetAppStats'](arg1);
}

export function GetAvailableApps() {
  return window['go']['api']['AppsAPI']['GetAvailableApps']();
}

export function GetConfiguredApps() {
  return window['go']['api']['AppsAPI']['GetConfiguredApps']();
}

export function GetContainerEnvironmentVars(arg1) {
  return window['go']['api']['AppsAPI']['GetContainerEnvironmentVars'](arg1);
}

export function GetContainerLogs(arg1) {
  return window['go']['api']['AppsAPI']['GetContainerLogs'](arg1);
}

export function GetContainerLogsAll(arg1) {
  return window['go']['api']['AppsAPI']['GetContainerLogsAll'](arg1);
}

export function GetContainerLogsTail(arg1, arg2) {
  return window['go']['api']['AppsAPI']['GetContainerLogsTail'](arg1, arg2);
}

export function GetDashboardSummary() {
  return window['go']['api']['AppsAPI']['GetDashboardSummary']();
}

export function GetRunningApps() {
  return window['go']['api']['AppsAPI']['GetRunningApps']();
}

export function OnStartup(arg1) {
  return window['go']['api']['AppsAPI']['OnStartup'](arg1);
}

export function OnStartupContext(arg1) {
  return window['go']['api']['AppsAPI']['OnStartupContext'](arg1);
}

export function RemoveApp(arg1) {
  return window['go']['api']['AppsAPI']['RemoveApp'](arg1);
}

export function RemoveAppInstance(arg1) {
  return window['go']['api']['AppsAPI']['RemoveAppInstance'](arg1);
}

export function RestartApp(arg1) {
  return window['go']['api']['AppsAPI']['RestartApp'](arg1);
}

export function SetContext(arg1) {
  return window['go']['api']['AppsAPI']['SetContext'](arg1);
}

export function StartApp(arg1) {
  return window['go']['api']['AppsAPI']['StartApp'](arg1);
}

export function StopApp(arg1) {
  return window['go']['api']['AppsAPI']['StopApp'](arg1);
}
