// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function DeployApp(arg1:string,arg2:Record<string, string>):Promise<void>;

export function DeployAppWithProxies(arg1:string,arg2:Record<string, string>,arg3:Array<string>):Promise<Array<Record<string, any>>>;

export function DeployAppWithProxiesSelective(arg1:string,arg2:string,arg3:Array<string>):Promise<Array<Record<string, any>>>;

export function DeployAppWithProxy(arg1:Record<string, any>):Promise<Record<string, any>>;

export function DeployAppWithProxyId(arg1:string,arg2:Record<string, string>,arg3:string):Promise<void>;

export function GetAppCredentials(arg1:string):Promise<Record<string, string>>;

export function GetAppInstances(arg1:string):Promise<Array<Record<string, any>>>;

export function GetAppLogs(arg1:string,arg2:number):Promise<string>;

export function GetAppStats(arg1:string):Promise<Record<string, any>>;

export function GetAvailableApps():Promise<Record<string, any>>;

export function GetConfiguredApps():Promise<Array<Record<string, any>>>;

export function GetContainerEnvironmentVars(arg1:string):Promise<Record<string, string>>;

export function GetContainerLogs(arg1:string):Promise<string>;

export function GetContainerLogsAll(arg1:string):Promise<string>;

export function GetContainerLogsTail(arg1:string,arg2:number):Promise<string>;

export function GetDashboardSummary():Promise<Record<string, any>>;

export function GetRunningApps():Promise<Array<Record<string, any>>>;

export function OnStartup(arg1:context.Context):Promise<void>;

export function OnStartupContext(arg1:context.Context):Promise<void>;

export function RemoveApp(arg1:string):Promise<void>;

export function RemoveAppInstance(arg1:string):Promise<void>;

export function RestartApp(arg1:string):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function StartApp(arg1:string):Promise<void>;

export function StopApp(arg1:string):Promise<void>;
