// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProxy(arg1, arg2, arg3) {
  return window['go']['api']['ProxyAPI']['AddProxy'](arg1, arg2, arg3);
}

export function ConfirmRemoveProxy(arg1) {
  return window['go']['api']['ProxyAPI']['ConfirmRemoveProxy'](arg1);
}

export function GetAppsRunningOnProxies(arg1) {
  return window['go']['api']['ProxyAPI']['GetAppsRunningOnProxies'](arg1);
}

export function GetConfiguredAppsForProxy() {
  return window['go']['api']['ProxyAPI']['GetConfiguredAppsForProxy']();
}

export function GetProxyContainers(arg1) {
  return window['go']['api']['ProxyAPI']['GetProxyContainers'](arg1);
}

export function ListProxies() {
  return window['go']['api']['ProxyAPI']['ListProxies']();
}

export function OnStartup(arg1) {
  return window['go']['api']['ProxyAPI']['OnStartup'](arg1);
}

export function RemoveProxy(arg1) {
  return window['go']['api']['ProxyAPI']['RemoveProxy'](arg1);
}

export function SetContext(arg1) {
  return window['go']['api']['ProxyAPI']['SetContext'](arg1);
}

export function TestProxy(arg1) {
  return window['go']['api']['ProxyAPI']['TestProxy'](arg1);
}
