// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function AddProxy(arg1:string,arg2:boolean,arg3:Array<string>):Promise<Record<string, any>>;

export function ConfirmRemoveProxy(arg1:string):Promise<void>;

export function GetAppsRunningOnProxies(arg1:Array<string>):Promise<Array<string>>;

export function GetConfiguredAppsForProxy():Promise<Array<Record<string, any>>>;

export function GetProxyContainers(arg1:string):Promise<Array<Record<string, any>>>;

export function ListProxies():Promise<Array<Record<string, any>>>;

export function OnStartup(arg1:context.Context):Promise<void>;

export function RemoveProxy(arg1:string):Promise<Record<string, any>>;

export function SetContext(arg1:context.Context):Promise<void>;

export function TestProxy(arg1:string):Promise<Record<string, any>>;
