// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';
import {context} from '../models';

export function GetSettings():Promise<api.AppSettings>;

export function OnStartup(arg1:context.Context):Promise<void>;
