// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSettings() {
  return window['go']['api']['SettingsAPI']['GetSettings']();
}

export function OnStartup(arg1) {
  return window['go']['api']['SettingsAPI']['OnStartup'](arg1);
}
